package flappybird;

import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author CHRISTIAN
 */
public class NewJPanel extends javax.swing.JPanel {
    private Controller controller;
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonNuevoJuego = new javax.swing.JToggleButton();

        setToolTipText("Flappy Quetzal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(680, 460));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        botonNuevoJuego.setBackground(new java.awt.Color(102, 102, 255));
        botonNuevoJuego.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        botonNuevoJuego.setForeground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        botonNuevoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flappybird/nuevojuego.png"))); // NOI18N
        botonNuevoJuego.setAlignmentY(0.0F);
        botonNuevoJuego.setBorder(null);
        botonNuevoJuego.setBorderPainted(false);
        botonNuevoJuego.setContentAreaFilled(false);
        botonNuevoJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonNuevoJuego.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonNuevoJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoJuegoMouseClicked(evt);
            }
        });
        botonNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoJuegoActionPerformed(evt);
            }
        });
        add(botonNuevoJuego);
        botonNuevoJuego.setBounds(140, 420, 221, 69);
        botonNuevoJuego.getAccessibleContext().setAccessibleName("nuevoJuego");
        botonNuevoJuego.getAccessibleContext().setAccessibleParent(botonNuevoJuego);

        getAccessibleContext().setAccessibleName("nuevojuego");
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void botonNuevoJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoJuegoMouseClicked
        
    }//GEN-LAST:event_botonNuevoJuegoMouseClicked

    private void botonNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoJuegoActionPerformed
        
        //controller.mostrar();
        
        try{
            
            controller.jugar();
        }
        catch(Exception e){
            controller.mostrar();
        }
    }//GEN-LAST:event_botonNuevoJuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonNuevoJuego;
    // End of variables declaration//GEN-END:variables
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        ImageIcon img = new ImageIcon("fondomenu.jpg");
        g.drawImage(img.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
    }
}
